"""
Synthetic Scenario Validation for Root Cause Analysis Engine
Tests end-to-end RCA against synthetic telemetry generated by the Virtual Industrial Simulator.
"""

from datetime import datetime, timezone, timedelta
import numpy as np
import pytest

from services.schemas import RootCauseType
from services.simulation.config import MachineSpec
from services.simulation.machine import SimulatedMachine
from services.simulation.scenarios import SimulationScenarioInstance, ScenarioType
from services.diagnostics.engine import get_rca_engine


def generate_scenario_telemetry(scenario_type: ScenarioType, duration_ticks: int = 25):
    """Generates synthetic physics telemetry stream using the factory simulator."""
    spec = MachineSpec(
        machine_id="M03",
        name="CNC Milling Unit 3",
        line_id="LINE_01",
        machine_type="CNC",
        nominal_power_kw=15.0,
        nominal_rpm=1500.0,
        nominal_temp_c=45.0,
        nominal_vib_mms=1.8,
        nominal_current_a=20.0,
        nominal_voltage_v=400.0,
        nominal_pressure_bar=2.5,
        nominal_output_rate=50.0,
    )
    rng = np.random.default_rng(42)
    machine = SimulatedMachine(spec=spec, rng=rng)

    scenario = SimulationScenarioInstance(
        scenario_type=scenario_type,
        machine_id="M03",
        severity=0.85,
        duration_sim_seconds=300.0,
    )

    t0 = datetime(2026, 9, 29, 14, 0, 0, tzinfo=timezone.utc)
    scenario.start(machine, current_sim_time=0.0)

    records = []
    anomaly_context = {}
    if scenario_type == ScenarioType.SENSOR_ANOMALY:
        anomaly_context = {"anomaly_type": "SENSOR_ANOMALY", "triggered_signals": ["vibration"]}

    for tick in range(duration_ticks):
        current_time = t0 + timedelta(seconds=tick * 5)
        # advance physics
        scenario.update(machine, dt_seconds=5.0)
        machine.step_physics(dt_seconds=5.0)
        tel = machine.generate_telemetry(timestamp=current_time)
        records.append(tel)

    baselines = {
        "temperature": (45.0, 1.2),
        "vibration": (1.8, 0.15),
        "current": (20.0, 0.8),
        "power_kw": (12.0, 0.4),
        "load": (1.0, 0.05),
        "efficiency": (100.0, 1.5),
        "pressure": (2.5, 0.1),
        "rpm": (1500.0, 15.0),
    }

    return records, baselines, anomaly_context


def test_scenario_normal_factory():
    engine = get_rca_engine()
    records, baselines, ctx = generate_scenario_telemetry(ScenarioType.NORMAL, duration_ticks=20)
    report = engine.analyze_from_telemetry(records, baselines, machine_id="M03", anomaly_context=ctx)

    # In normal conditions, system must NOT falsely blame physical mechanisms
    assert report.likely_cause == RootCauseType.UNKNOWN
    assert report.confidence == "LOW"


def test_scenario_bearing_degradation():
    engine = get_rca_engine()
    records, baselines, ctx = generate_scenario_telemetry(ScenarioType.BEARING_DEGRADATION, duration_ticks=25)
    report = engine.analyze_from_telemetry(records, baselines, machine_id="M03", anomaly_context=ctx)

    # Top-1 cause must be BEARING_DEGRADATION
    assert report.likely_cause == RootCauseType.BEARING_DEGRADATION
    assert report.evidence_score >= 0.70
    assert report.ranking[0].cause == RootCauseType.BEARING_DEGRADATION
    assert report.confidence in ["HIGH", "MEDIUM"]


def test_scenario_cooling_degradation():
    engine = get_rca_engine()
    records, baselines, ctx = generate_scenario_telemetry(ScenarioType.COOLING_DEGRADATION, duration_ticks=25)
    report = engine.analyze_from_telemetry(records, baselines, machine_id="M03", anomaly_context=ctx)

    # Top-1 cause must be COOLING_DEGRADATION
    assert report.likely_cause == RootCauseType.COOLING_DEGRADATION
    assert report.evidence_score >= 0.70
    assert report.ranking[0].cause == RootCauseType.COOLING_DEGRADATION


def test_scenario_overload():
    engine = get_rca_engine()
    records, baselines, ctx = generate_scenario_telemetry(ScenarioType.OVERLOAD, duration_ticks=25)
    report = engine.analyze_from_telemetry(records, baselines, machine_id="M03", anomaly_context=ctx)

    # Top-1 cause must be OVERLOAD
    assert report.likely_cause == RootCauseType.OVERLOAD
    assert report.evidence_score >= 0.70
    assert report.ranking[0].cause == RootCauseType.OVERLOAD


def test_scenario_sensor_anomaly():
    engine = get_rca_engine()
    records, baselines, ctx = generate_scenario_telemetry(ScenarioType.SENSOR_ANOMALY, duration_ticks=20)
    report = engine.analyze_from_telemetry(records, baselines, machine_id="M03", anomaly_context=ctx)

    # Top-1 cause must be SENSOR_ANOMALY
    assert report.likely_cause == RootCauseType.SENSOR_ANOMALY
    assert report.evidence_score >= 0.75
    assert report.ranking[0].cause == RootCauseType.SENSOR_ANOMALY
