"""add idempotency hash and digital twin telemetry columns

Revision ID: 0c6d6de99a81
Revises: 0cf3bbaa6bfc
Create Date: 2026-09-29 08:04:25.533593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6d6de99a81'
down_revision: Union[str, Sequence[str], None] = '0cf3bbaa6bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_states', sa.Column('freshness', sa.String(length=20), server_default='FRESH', nullable=False))
    op.add_column('machine_states', sa.Column('maintenance_status', sa.String(length=50), server_default='OK', nullable=False))
    op.add_column('machine_states', sa.Column('temperature', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('vibration', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('pressure', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('current', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('voltage', sa.Float(), server_default='400.0', nullable=False))
    op.add_column('machine_states', sa.Column('rpm', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('power_kw', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('efficiency', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('machine_states', sa.Column('output_rate', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('machine_states', sa.Column('last_telemetry_id', sa.Integer(), nullable=True))
    op.add_column('machine_states', sa.Column('last_telemetry_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telemetry', sa.Column('idempotency_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_telemetry_idempotency_hash'), 'telemetry', ['idempotency_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_idempotency_hash'), table_name='telemetry')
    op.drop_column('telemetry', 'idempotency_hash')
    op.drop_column('machine_states', 'last_telemetry_timestamp')
    op.drop_column('machine_states', 'last_telemetry_id')
    op.drop_column('machine_states', 'output_rate')
    op.drop_column('machine_states', 'efficiency')
    op.drop_column('machine_states', 'power_kw')
    op.drop_column('machine_states', 'rpm')
    op.drop_column('machine_states', 'voltage')
    op.drop_column('machine_states', 'current')
    op.drop_column('machine_states', 'pressure')
    op.drop_column('machine_states', 'vibration')
    op.drop_column('machine_states', 'temperature')
    op.drop_column('machine_states', 'maintenance_status')
    op.drop_column('machine_states', 'freshness')
    # ### end Alembic commands ###
