"""add pressure and load columns and machine attributes

Revision ID: 0cf3bbaa6bfc
Revises: 21ae6538b2ef
Create Date: 2026-09-29 07:48:02.264326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf3bbaa6bfc'
down_revision: Union[str, Sequence[str], None] = '21ae6538b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('rated_load', sa.Float(), nullable=False))
    op.add_column('machines', sa.Column('maintenance_status', sa.String(length=50), nullable=False))
    op.add_column('telemetry', sa.Column('pressure', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('load', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'load')
    op.drop_column('telemetry', 'pressure')
    op.drop_column('machines', 'maintenance_status')
    op.drop_column('machines', 'rated_load')
    # ### end Alembic commands ###
