"""create initial nexus tables

Revision ID: 21ae6538b2ef
Revises: 
Create Date: 2026-09-29 07:36:54.912885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ae6538b2ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('nominal_power_kw', sa.Float(), nullable=False),
    sa.Column('nominal_rpm', sa.Float(), nullable=False),
    sa.Column('max_temperature_c', sa.Float(), nullable=False),
    sa.Column('max_vibration_mms', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_line_id'), 'machines', ['line_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_detected', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('primary_metric', sa.String(length=50), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_machine_id'), 'anomalies', ['machine_id'], unique=False)
    op.create_table('machine_states',
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('load_factor', sa.Float(), nullable=False),
    sa.Column('temperature_trend', sa.Float(), nullable=False),
    sa.Column('vibration_trend', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('predicted_failure_probability', sa.Float(), nullable=False),
    sa.Column('predicted_health_score', sa.Float(), nullable=False),
    sa.Column('remaining_useful_life_hours', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_machine_id'), 'predictions', ['machine_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_impact', sa.String(length=50), nullable=False),
    sa.Column('cost_impact', sa.String(length=20), nullable=False),
    sa.Column('production_loss_pct', sa.Float(), nullable=False),
    sa.Column('recommended_deadline_hours', sa.Float(), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_machine_id'), 'recommendations', ['machine_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('target_machine_id', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('baseline_production_units', sa.Float(), nullable=False),
    sa.Column('simulated_production_units', sa.Float(), nullable=False),
    sa.Column('production_loss_pct', sa.Float(), nullable=False),
    sa.Column('simulated_failure_probability', sa.Float(), nullable=False),
    sa.Column('risk_reduction_pct', sa.Float(), nullable=False),
    sa.Column('affected_cascade_machines', sa.JSON(), nullable=False),
    sa.Column('recovery_time_hours', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('vibration', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('output_rate', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('quality_indicator', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_machine_id'), 'telemetry', ['machine_id'], unique=False)
    op.create_index('ix_telemetry_machine_time', 'telemetry', ['machine_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index('ix_telemetry_machine_time', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_machine_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_recommendations_machine_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_machine_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('machine_states')
    op.drop_index(op.f('ix_anomalies_machine_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_machines_line_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
